const path=require('path'), fs_=require('fs');
const ROOT=path.join(__dirname,'..','..');
const APP=process.env.APP_HTML||path.join(ROOT,'src','app','index.html');
const OFFLINE=process.env.OFFLINE_HTML||path.join(ROOT,'public','index.html');
const LIB_H2C=path.join(ROOT,'vendor','html2canvas.min.js');
const LIB_JSPDF=path.join(ROOT,'vendor','jspdf.umd.min.js');
const TMP=process.env.TEST_TMP||path.join(ROOT,'.test-out');
const T=n=>{fs_.mkdirSync(path.dirname(path.join(TMP,n)),{recursive:true});return path.join(TMP,n)};
const WRAP=n=>{const p=T(n); if(!fs_.existsSync(p)) fs_.writeFileSync(p,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0}[hidden]{display:none!important}</style></head><body>'+fs_.readFileSync(APP,'utf8')+'</body></html>'); return p};
const { chromium } = require('playwright'); const fs=require('fs');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route(/cdnjs|fonts/, r=>r.fulfill({body:''}));
const body=fs.readFileSync(APP,'utf8');
fs.writeFileSync(T('t10.html'),'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0}[hidden]{display:none!important}</style></head><body>'+body+'</body></html>');
await p.goto('file://'+WRAP('t10.html'));await p.waitForTimeout(400);
await p.evaluate(()=>{S.logs[today()]={day:3,night:1,bloody:2,urg:1,blood:1,well:1,extra:[],pain:3,gas:"없음",fatigue:"없음",temp:"38.4",pulse:"104",other:[],memo:""};render()});
await p.waitForTimeout(300); await p.screenshot({path:T('t10_plan.png'),fullPage:true});
await p.evaluate(()=>{S.tab="food";S.foodSub="label";LB={...LB,step:"done",name:"도시락(돼지불고기)",text:"쌀, 돼지고기, 간장, 설탕. 이 제품은 메밀, 대두, 새우를 사용한 제품과 같은 제조시설에서 제조하고 있습니다.",nutri:{basis:"총 내용량 400g",basisAmt:400,basisUnit:"g",kcal:680,fat:19,sodium:1171,protein:14,fiber:null,sugar:null,polyol:null,trans:0,calcium:null},eat:"400"};S.profile.allergies=["shrimp"];lbRun();render()});
await p.waitForTimeout(300); await p.screenshot({path:T('t10_label.png'),fullPage:true});
console.log(errs); await b.close()})();
