const path=require('path'), fs_=require('fs');
const ROOT=path.join(__dirname,'..','..');
const APP=process.env.APP_HTML||path.join(ROOT,'src','app','index.html');
const OFFLINE=process.env.OFFLINE_HTML||path.join(ROOT,'public','index.html');
const LIB_H2C=path.join(ROOT,'vendor','html2canvas.min.js');
const LIB_JSPDF=path.join(ROOT,'vendor','jspdf.umd.min.js');
const TMP=process.env.TEST_TMP||path.join(ROOT,'.test-out');
const T=n=>{fs_.mkdirSync(path.dirname(path.join(TMP,n)),{recursive:true});return path.join(TMP,n)};
const WRAP=n=>{const p=T(n); if(!fs_.existsSync(p)) fs_.writeFileSync(p,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0}[hidden]{display:none!important}</style></head><body>'+fs_.readFileSync(APP,'utf8')+'</body></html>'); return p};
const { chromium } = require('playwright'); const fs=require('fs');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route(/cdnjs|fonts/, r=>r.fulfill({body:''}));
await p.goto('file://'+WRAP('t13.html'));await p.waitForTimeout(400);
await p.evaluate(()=>{S.consent={date:today(),ai:false};S.plan=null;render()});
await p.click('.mrow[data-k="0"]'); await p.waitForTimeout(300);
await p.click('[data-act=rateSet][data-j="0"][data-v=bad]'); await p.click('[data-act=rateSave]'); await p.waitForTimeout(200);
await p.click('[data-act=badSym][data-v=blood]');await p.click('[data-act=badSym][data-v=allergy]');
await p.evaluate(()=>{const s=document.querySelector('#sheetRoot .sheet')||document.querySelector('#sheetRoot > *'); s&&s.scrollTo&&s.scrollTo(0,9999)}); await p.waitForTimeout(400);
await p.screenshot({path:T('n_bad2.png')});
console.log(await p.evaluate(()=>{const e=document.querySelector('#sheetRoot *');const st=getComputedStyle(document.querySelector('#sheetRoot .sheet')||e);return [st.maxHeight,st.overflowY]}));
console.log(await p.evaluate(()=>FOODS.filter(f=>["banana","pumpkin","zucchini"].includes(f.id)).map(f=>[f.id,foodStatus(f).reasons])));
console.log(errs);await b.close()})();
