const path=require('path'), fs_=require('fs');
const ROOT=path.join(__dirname,'..','..');
const APP=process.env.APP_HTML||path.join(ROOT,'src','app','index.html');
const OFFLINE=process.env.OFFLINE_HTML||path.join(ROOT,'public','index.html');
const LIB_H2C=path.join(ROOT,'vendor','html2canvas.min.js');
const LIB_JSPDF=path.join(ROOT,'vendor','jspdf.umd.min.js');
const TMP=process.env.TEST_TMP||path.join(ROOT,'.test-out');
const T=n=>{fs_.mkdirSync(path.dirname(path.join(TMP,n)),{recursive:true});return path.join(TMP,n)};
const WRAP=n=>{const p=T(n); if(!fs_.existsSync(p)) fs_.writeFileSync(p,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0}[hidden]{display:none!important}</style></head><body>'+fs_.readFileSync(APP,'utf8')+'</body></html>'); return p};
const { chromium } = require('playwright'); const fs=require('fs');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
await p.route(/cdnjs|fonts/, r=>r.fulfill({body:''}));
const body=fs.readFileSync(APP,'utf8');
fs.writeFileSync(T('t7.html'),'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0}[hidden]{display:none!important}</style></head><body>'+body+'</body></html>');
await p.goto('file://'+WRAP('t7.html'));await p.waitForTimeout(500);await p.evaluate(()=>{S.consent={date:today(),ai:true};render()});
const r=await p.evaluate(()=>{
  const out={};
  S.profile.allergies=['wheat','egg','dairy']; 
  const lc=labelCheck("소맥분, 난백분, 유청단백분말, 전분, 정제소금");
  out.label=[lc.overall,lc.rows.map(r=>r.title+":"+r.found.join("/"))];
  out.label2=labelCheck("쌀, 정제소금").rows.map(r=>r.title+":"+r.found.join("/"));
  S.profile.allergies=[]; S.profile.lactose=true;
  out.menu=[["전복죽",[]],["백김치",["배추","무"]],["닭갈비",["닭고기","양배추"]],["유당분해우유",[]],["김치전",["밀가루","김치"]]].map(([n,g])=>[n,ruleCheck({name:n,ingr:g,cook:""})]);
  out.act1=activity({day:2,night:5,bloody:0,urg:2,blood:0,well:1,extra:[],pain:9});
  out.act2=activity({day:3,night:0,bloody:0,urg:0,blood:0,well:0,extra:[]});
  out.act3=activity({day:4,night:1,bloody:1,urg:1,blood:1,well:0,extra:[]});
  out.d1=dangerSignals({day:3,night:0,bloody:2,temp:"39.2",pulse:"118",pain:3});
  out.d2=dangerSignals({day:8,night:2,bloody:7,temp:"37.6",pulse:"",pain:3});
  out.d3=dangerSignals({day:14,night:2,bloody:3,temp:"",pulse:"95",pain:3});
  S.weights=[{date:today(),kg:58}]; out.water=[targets().water,targets().waterSrc];
  S.stageMode=1;
  out.st=["nurungji","radish","salmon","beef","milk","soy_milk","somen","button_mushroom","perilla_oil","crab","pumpkin_porridge","chicken_porridge","mandarin","napa"].map(id=>[id,FOOD[id].fi,foodStatus(FOOD[id]).level,foodStatus(FOOD[id]).reasons.join("|")]);
  out.missing=FOODS.filter(f=>f.missing.length).map(f=>f.id);
  out.noicon=FOODS.filter(f=>!FICON[f.id]).map(f=>f.id);
  out.sample=samplePlan().days[0].meals.map(m=>m.slot+":"+m.title);
  out.viol=samplePlan().days.flatMap(d=>d.meals.flatMap(m=>m.items.filter(([id,g])=>FOOD[id].fi*g/100>=2).map(x=>m.title+x)));
  return out});
console.log(JSON.stringify(r,null,0).replace(/\],\"/g,'],\n"'));
// meds + nutri
await p.evaluate(()=>{S.stageMode="auto";S.profile.meds=["ssz","steroid","chol"];S.tab="nutri";render()});
await p.waitForTimeout(300); await p.screenshot({path:T('t7_nutri.png'),fullPage:true});
// back nav
await p.evaluate(()=>{S.tab="plan";render()}); await p.click('.mrow[data-k="0"]'); await p.waitForTimeout(100);
console.log('open meal', await p.evaluate(()=>[SCR&&SCR.name,history.length,NAV.depth]));
await p.goBack(); await p.waitForTimeout(200);
console.log('after back', await p.evaluate(()=>[SCR,NAV.depth]));
await p.click('.tile[data-act=wizard]'); await p.waitForTimeout(100);
await p.click('[data-act=step][data-k=day][data-v="1"]');
await p.goBack(); await p.waitForTimeout(200);
console.log('wizard dirty back', await p.evaluate(()=>[SCR&&SCR.name,!!document.querySelector('#sheetRoot').firstChild,NAV.depth]));
await p.goBack(); await p.waitForTimeout(200);
console.log('back again', await p.evaluate(()=>[SCR&&SCR.name,!!document.querySelector('#sheetRoot').firstChild,NAV.depth]));
await p.click('[data-act=back]'); await p.waitForTimeout(150); await p.click('[data-act=wzDiscard]'); await p.waitForTimeout(300);
console.log('discard', await p.evaluate(()=>[SCR,!!document.querySelector('#sheetRoot').firstChild,NAV.depth,NAV.skip]));
// double tap
await p.click('.tile[data-act=wizard]'); await p.waitForTimeout(100); for(let i=0;i<3;i++) await p.click('[data-act=wzNext]');
const stepBefore=await p.evaluate(()=>WZ.step);
await p.dblclick('[data-act=set][data-k=urg][data-v="1"]'); await p.waitForTimeout(500);
console.log('double tap step', stepBefore, await p.evaluate(()=>WZ.step));
// font size
await p.evaluate(()=>{draft=null;SCR=null;S.fontSize="xl";S.tab="plan";render()}); await p.waitForTimeout(400);
await p.screenshot({path:T('t7_xl_plan.png')});
await p.evaluate(()=>{SCR={name:"set-about"};render()}); await p.waitForTimeout(400);
await p.screenshot({path:T('t7_xl_about.png'),fullPage:true});
await p.evaluate(()=>{SCR=null;S.tab="food";render()}); await p.waitForTimeout(300); await p.click('.fcard'); await p.waitForTimeout(400);
await p.screenshot({path:T('t7_xl_sheet.png')});
console.log('hscroll', await p.evaluate(()=>document.documentElement.scrollWidth));
console.log('errors',errs); await b.close()})();
